### ISSUE TITLE
Implement Google site verification via domain provider

### ISSUE THREAD

**Issue by JonathanXDR** [Pascal1414/ffvgs#36]
Currently, the site verification is done via a static html file. Please fix that by adding a TXT record to your list of DNS records for your domain provider. Find more infos [here](https://support.google.com/webmasters/answer/9008080?hl=en#choose_method&zippy=%2Cdomain-name-provider).

**Comment by Pascal1414** [comment]
Thank you a  lot for your help but please mind your own business

**Comment by JonathanXDR** [comment]
This is not acceptable and not considered as clean code

**Comment by Pascal1414** [comment]
This is an official feature from google and defnitely considered as clean code

**Comment by JonathanXDR** [comment]
![image](https://github.com/Pascal1414/ffvgs/assets/73559516/8cef51ce-50bf-44f0-97f6-7cb52c3f475a)

**Comment by JonathanXDR** [comment]
Hello, is there any update for this issue?

**Comment by Pascal1414** [comment]
I have contacted the host about the problem that I couldn't add a dns record of the type TXT. I hope to hear from them soon.

**Comment by JonathanXDR** [comment]
Alright thanks for your assistance in this matter

**Comment by JonathanXDR** [comment]
This issue won't count as fixed until the implementation is done
